### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by sedrubal** [photo/frontend#1585] opened 2015-11-02 22:41 UTC
Hi,

I think this project is very great, but it seems that it is dead and there is no maintenance right now. Am I right? Are you planning to revive the project?

Thanks

**Comment by kvaps** [comment] 2015-11-04 22:25
Hi, I also very interested in this issue. Right now I'm faced with a choice Trovebox as the main hosting for my photos.
Thanks.

**Comment by joephein** [comment] 2015-11-05 07:42
I suggest users that want to have a independent cloud solution for their photo's to have a look at ownCloud and the Gallery app that can be found on github: https://github.com/owncloud/gallery/ This project is very active and while it is still missing many functionalities that Trovebox and Picturelife have/had with a bit of crowdfunding it could get there. Maybe forces can be joined and code from the trovebox frontend can be used to improve the gallery app for owncloud?

**Comment by sedrubal** [comment] 2015-11-05 13:45
:+1:

**Comment by jmathai** [comment] 2015-11-05 19:10
This is a duplicate of #1570. I'm not sure there's enough interest in keeping the project alive. I'm not sure how any attention could be shifted over to OwnCloud or another similar alternative though.

**Closed by jmathai** 2015-11-05 19:10 UTC
